#!/usr/bin/env python3
"""
Base Conductor - Abstract orchestration framework.

This module provides the base class for orchestration conductors that
coordinate AI agents to work collaboratively on tasks.
"""

import re
import json
from abc import ABC, abstractmethod
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional, Callable, Awaitable

from agents import BaseAgent, AgentResponse, create_agent


# Type alias for output handlers
OutputHandler = Callable[[Dict[str, Any]], Awaitable[None]]


class BaseConductor(ABC):
    """
    Abstract base class for orchestration conductors.

    Conductors manage the workflow of AI agents working together on tasks,
    handling project organization, agent coordination, and output management.
    """

    def __init__(self, agent_preset: str = "claude", base_dir: Optional[Path] = None):
        """
        Initialize the conductor.

        Args:
            agent_preset: Name of the agent preset to use (e.g., 'claude', 'kiro')
            base_dir: Base directory for project outputs
        """
        self.agent_preset = agent_preset
        self.agent = create_agent(agent_preset)
        self.output_handlers: List[OutputHandler] = []
        self.base_dir = base_dir or Path.cwd() / 'projects_master'
        self.base_dir.mkdir(exist_ok=True)

        # Current project state
        self.working_dir: Optional[Path] = None
        self.project_name: Optional[str] = None

        # Communication log
        self.communications: List[Dict[str, Any]] = []

    def add_output_handler(self, handler: OutputHandler) -> None:
        """Add a handler to receive real-time output."""
        self.output_handlers.append(handler)

    def remove_output_handler(self, handler: OutputHandler) -> None:
        """Remove an output handler."""
        if handler in self.output_handlers:
            self.output_handlers.remove(handler)

    def _sanitize_project_name(self, task: str) -> str:
        """Create a safe folder name from the task description."""
        name = task.lower()

        # Remove common words
        stop_words = ['create', 'a', 'an', 'the', 'build', 'make', 'develop', 'implement']
        words = name.split()
        words = [w for w in words if w not in stop_words]
        name = ' '.join(words[:4])  # Take first 4 meaningful words

        # Clean up for filesystem
        name = re.sub(r'[^\w\s-]', '', name)
        name = re.sub(r'[-\s]+', '-', name)
        name = name.strip('-')

        # Add timestamp for uniqueness
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

        return f"{name}_{timestamp}"

    def _setup_project_directory(self, task: str) -> None:
        """Create a new project directory for this task."""
        self.project_name = self._sanitize_project_name(task)
        self.working_dir = self.base_dir / self.project_name
        self.working_dir.mkdir(exist_ok=True)

        # Create subdirectories
        (self.working_dir / 'src').mkdir(exist_ok=True)
        (self.working_dir / 'docs').mkdir(exist_ok=True)
        (self.working_dir / 'tests').mkdir(exist_ok=True)

        # Create a README with task info
        readme_content = f"""# {task}

Generated by LLM Conductor on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Using agent: {self.agent.name}

## Task Description
{task}

## Project Structure
```
{self.project_name}/
├── src/         # Source code files
├── docs/        # Documentation and analysis
├── tests/       # Test files
└── README.md    # This file
```

## Files Generated
_Files will be listed here as they are created_
"""
        (self.working_dir / 'README.md').write_text(readme_content)

        print(f"\n📁 Created project folder: {self.working_dir}")
        print(f"   Project name: {self.project_name}")
        print(f"   Agent: {self.agent.name}")

    async def broadcast(self, data: Dict[str, Any]) -> None:
        """Send data to all output handlers."""
        for handler in self.output_handlers:
            try:
                await handler(data)
            except Exception:
                pass  # Don't let handler errors stop the orchestration

    async def broadcast_project_info(self) -> None:
        """Send project folder information to output handlers."""
        await self.broadcast({
            'type': 'project_created',
            'project_name': self.project_name,
            'project_path': str(self.working_dir),
            'agent': self.agent.name,
            'timestamp': datetime.now().strftime('%H:%M:%S')
        })

    async def run_agent(self, prompt: str, role: str,
                        print_only: bool = False,
                        skip_permissions: bool = True) -> AgentResponse:
        """
        Run the agent with the given prompt.

        Args:
            prompt: The prompt to send to the agent
            role: Role description for display (e.g., "Analyst", "Implementer")
            print_only: If True, agent should only analyze/print (no file changes)
            skip_permissions: If True, skip permission prompts

        Returns:
            AgentResponse with the results
        """
        print(f"\n{'='*70}")
        print(f"🤖 {self.agent.name}-{role} SPEAKING:")
        print(f"{'='*70}")

        if print_only:
            print(f"\nPROMPT:\n{'-'*70}")
            print(prompt)
            print(f"{'-'*70}\n")

        # Determine working directory based on role
        if "Analyst" in role or "Reviewer" in role or "Designer" in role:
            cwd = self.working_dir / 'docs' if self.working_dir else None
        else:
            cwd = self.working_dir / 'src' if self.working_dir else None

        # Execute the agent
        response = await self.agent.execute(
            prompt=prompt,
            working_dir=cwd,
            print_only=print_only,
            skip_permissions=skip_permissions
        )

        # Display response
        if response.output:
            print(f"RESPONSE:")
            print(f"{'-'*70}")
            print(response.output)
            print(f"{'-'*70}")

        # Store communication
        self.communications.append({
            'agent': f"{self.agent.name}-{role}",
            'timestamp': datetime.now().isoformat(),
            'prompt': prompt,
            'response': response.output,
            'success': response.success,
            'duration': response.duration,
            'type': 'analysis' if print_only else 'action'
        })

        # Notify handlers
        await self.broadcast({
            'type': 'agent_output',
            'tool': self.agent_preset,
            'agent': f"{self.agent.name}-{role}",
            'line': f"{role}: {response.output[:100]}..." if response.output else f"{role}: (no output)",
            'success': response.success,
            'timestamp': datetime.now().strftime('%H:%M:%S')
        })

        return response

    def _update_readme_with_files(self) -> None:
        """Update the project README with the list of generated files."""
        if not self.working_dir:
            return

        all_files = []
        for subdir in ['src', 'docs', 'tests']:
            subpath = self.working_dir / subdir
            if subpath.exists():
                files = [f for f in subpath.iterdir() if f.is_file()]
                if files:
                    all_files.append(f"\n### {subdir}/")
                    for f in files:
                        try:
                            size = len(f.read_text())
                            all_files.append(f"- {f.name} ({size} chars)")
                        except Exception:
                            all_files.append(f"- {f.name}")

        readme_path = self.working_dir / 'README.md'
        if readme_path.exists():
            readme_content = readme_path.read_text()
            readme_content = readme_content.replace(
                "_Files will be listed here as they are created_",
                '\n'.join(all_files) if all_files else "_No files generated_"
            )
            readme_path.write_text(readme_content)

    def _save_communication_log(self, filename: str = "communication_log.json") -> Path:
        """Save the communication log to a JSON file."""
        if not self.working_dir:
            return Path()

        log_file = self.working_dir / "docs" / filename
        log_file.write_text(json.dumps(self.communications, indent=2))
        return log_file

    @abstractmethod
    async def orchestrate(self, task: str) -> Dict[str, Any]:
        """
        Orchestrate the task execution.

        This is the main entry point that subclasses must implement to
        define their specific orchestration workflow.

        Args:
            task: The task description to orchestrate

        Returns:
            Dictionary with orchestration results
        """
        pass
